apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wk9zy6dwq-go
  janus-idp.io/tekton: wk9zy6dwq-go
  backstage.io/kubernetes-id: wk9zy6dwq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wk9zy6dwq-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
